title: "Dialéctica Micro-Fractal"
description: "Una exploración de coherencia, agencia y autonomía en tiempos de colapso."
theme: just-the-docs

url: "https://nomosfractal.github.io/dialectica-micro-fractal"

just_the_docs:
  logo: "/assets/images/logo.png"
  favicon_ico: "/assets/images/favicon.ico"

  aux_nav:
    "Proyecto":
      - "Repositorio en GitHub": "https://github.com/nomosfractal/dialectica-micro-fractal"
      - "Licencia": "/LICENSE"

  collections:
    es:
      name: "Versión en Español"
      nav_order: 1
      permalink: "/es/:path/"
      output: true

collections:
  es:
    output: true
    permalink: "/es/:path/"
